= Changes to Xtensions
:toc:
:toclevels: 1
:toc-title: Version Overview:

== Version 1.3.0 (unreleased)

link:https://github.com/fraunhoferfokus/Xtensions/milestone/4?closed=1[Related GitHub issues]

=== Added 

- Extension methods `ifTrue`, `ifNullOrTrue`, `ifFalse` and `ifNullOrFalse` for the `Boolean` wrapper type (see book chapter <<./docs/functionality/16_primitives.adoc#testing-conditions-on-primitives,Testing Conditions on Primitive Values>>)
- General extension methods `asType`, `ifNotNull`, `recoverNull`/`requireNonNullElse`, and `recoverNull`/`requireNonNullElseGet` for objects (see book chapter <<./docs/functionality/17_objects.adoc#,Objects>>)
- Introduced `Try` type, which represents a computation result that may have failed. (book chapter <<./docs/functionality/18_try.adoc#,Try>>)
- Added the `OptionalBoolean` class, as a replacement for `Optional<Boolean>` (book chapter `<<./docs/functionality/01_optionals.adoc#_optionalboolean,OptionalBoolean>>)

== Version 1.2.0 - 2019-04-10

link:https://github.com/fraunhoferfokus/Xtensions/milestone/3?closed=1[Related GitHub issues]

=== Added 

- Added helpers for handling primitive values at the end of null-safe navigation chains

=== Changed

- Increased minimum Xtend version to 2.15, mainly due to build issues


== Version 1.1.0 - 2018-07-23

link:https://github.com/fraunhoferfokus/Xtensions/milestone/2?closed=1[Related GitHub issues]

=== Added 

- Added `combinations` and `combinationsWith` extension methods for `Iterator` and `Iterable` to generate cartesian products.
- Added `withoutAll` extension methods for `Iterable` and `Iterator` to filter elements from the source available in another `Iterable`.
- Added `partitionBy` extension methods for `Iterator` and `Iterable`, partitioning elements into two aggregates: selected and rejected.
- Added `Iterator`/`Iterable` extension methods `groupIntoListBy` and `groupIntoSetBy` to group elements by given classes.
- Added `into` extension methods to `Iterator`/`Iterable` to add elements to one or more ``Collection``s.
- Added `summarize` extension methods for ``PrimitiveIterator``s to compute count, min, max, average and sum of provided values.
- Added `streamRemainingExhaustive` extension method for ``PrimitiveIterator``s that is guaranteed to pull elements from the originating iterator.
- Functional factory methods for and in `LongIterable` and `DoubleIterable`.
- Added `mapOrGet` extension method for `Optional`.
- Added `forEach` method for object arrays to iterate over elements without instantiation of an iterator.

=== Changed
- Bumped Xtend minimum version to `2.13`


== Version 1.0.0 - 2018-03-02

=== Added 

Everything new 😊

- Extension methods for ``Optional``s
- Extension methods for Xtend ``IntegerRange``s
- Extension methods for primitive arrays
- Extension methods for Java ``Stream``s
- Extension methods for ``Iterable``s
- Extension methods for Java ``String``s
- Extension methods for Java ``Duration``s
- Extension methods for Xtend functions
- Extension methods for Java ``CompletableFuture``s
- Scheduling utilities
- Asynchronous execution utilities
- Primitive ``Iterable``s