= Changes to Xtensions
:toc:
:toclevels: 1
:toc-title: Version Overview:


== Version 1.1.0 (Unreleased)

link:https://github.com/fraunhoferfokus/Xtensions/milestone/2?closed=1[Related GitHub issues]

=== Added 

- Bumped Xtend minimum version to `2.13`
- Added `combinations` and `combinationsWith` extension methods for `Iterator` and `Iterable` to generate cartesian products.
- Added `withoutAll` extension methods for `Iterable` and `Iterator` to filter elements from the source available in another `Iterable`.
- Added `partitionBy` extension methods for `Iterator` and `Iterable`, partitioning elements into two aggregates: selected and rejected.
- Added `Iterator`/`Iterable` extension methods `groupIntoListBy` and `groupIntoSetBy` to group elements by given classes.
- Added `into` extension methods to `Iterator`/`Iterable` to add elements to one or more ``Collection``s.
- Added `summarize` extension methods for ``PrimitiveIterator``s to compute count, min, max, average and sum of provided values.
- Added `streamRemainingExhaustive` extension method for ``PrimitiveIterator``s that is guaranteed to pull elements from the originating iterator.
- Functional factory methods for and in `LongIterable` and `DoubleIterable`.
- Added `mapOrGet` extension method for `Optional`.
- Added `forEach` method for object arrays to iterate over elements without instantiation of an iterator.


== Version 1.0.0 - 2018-03-02

=== Added 

Everything new 😊

- Extension methods for ``Optional``s
- Extension methods for Xtend ``IntegerRange``s
- Extension methods for primitive arrays
- Extension methods for Java ``Stream``s
- Extension methods for ``Iterable``s
- Extension methods for Java ``String``s
- Extension methods for Java ``Duration``s
- Extension methods for Xtend functions
- Extension methods for Java ``CompletableFuture``s
- Scheduling utilities
- Asynchronous execution utilities
- Primitive ``Iterable``s