
== Xtensions Contribution Guide

External contributions in form of pull requests are welcome, if they include sufficient tests 
and documentation (JavaDoc and, if valuable, description to the link:README.adoc[README] or other AsciiDoc documentation). 
Please note that contributions may be rejected if they do not seem beneficial to the project. Please get in touch
beforehand (e.g. via issues) to get to know if a certain enhancement is regarded beneficial. +
Currently there are no preferred labels for the issues, this guide will be updated as soon
as the preferred labels are decided on.

Better code examples for the documentation are very welcome 😊.

=== Code of Conduct

Please be polite, this project uses the link:http://berlincodeofconduct.org[Berlin Code of Conduct]
to define acceptable and unacceptable behavior when interacting among one another.

=== Response Times

Please be aware that it may take a few days to react on issues and pull requests. This project is developed in spare time, 
so response time may vary.

=== License and IP

Contributions will be licensed under https://www.eclipse.org/legal/epl-2.0/[EPL 2.0].

In case this project is transferred to a vendor neutral organization, every contributor agrees 
up-front to transfer the rights of his/her contribution to redistribute and host the content 
and manage the IP of the overall project to this organization.