////
Copyright (c) 2017 Max Bureck (Fraunhofer FOKUS) and others.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html

Contributors:
    Max Bureck (Fraunhofer FOKUS) - initial text
////

= Xtensions Library
:toc: preamble
:toclevels: 3
:toc-title: Contents of this document:


image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["License : EPL v2.0", link=https://www.eclipse.org/legal/epl-2.0/] 
image:https://travis-ci.org/fraunhoferfokus/Xtensions.svg?branch=master["Build Status", link="https://travis-ci.org/fraunhoferfokus/Xtensions"] 
image:https://codecov.io/gh/fraunhoferfokus/Xtensions/branch/master/graph/badge.svg["Code Coverage", link="https://codecov.io/gh/fraunhoferfokus/Xtensions"]
//image:https://coveralls.io/repos/github/fraunhoferfokus/Xtensions/badge.svg?branch=master["Code Coverage", link="https://coveralls.io/github/fraunhoferfokus/Xtensions?branch=master"]



This library is mainly a collection of https://www.eclipse.org/xtend/[Xtend] extension methods
for classes in the Java 8 standard library and the Xtend standard library. A few goals are:

* Adding extension methods to Java 8 JDK types to make them work more naturally with Xtend
* Making a select few Java 9 methods available on Java 8
* Providing support for iteration over primitive values without resort to boxing
* Adding some useful additional methods to existing standard JDK and Xtend standard lib classes

Note that the policy of using functional interfaces is the following:

* Generally, the Xtend interfaces defined in http://javadoc.io/page/org.eclipse.xtext/org.eclipse.xtext.xbase.lib/latest/org/eclipse/xtext/xbase/lib/Functions.html[`org.eclipse.xtext.xbase.lib.Functions`] 
  are preferred over the ones defined in JDK 8 package.
  http://docs.oracle.com/javase/8/docs/api/index.html?java/util/function/package-summary.html[`java.util.function`]
* When primitive values are involved, the specialized interfaces from `java.util.function` are preferred.
* When a shim over JDK 8 APIs is provided and Xtend interfaces would introduce unnecessary object allocations
  the JDK interfaces are preferred.

== Usage

In the following, we will show how to add the Xtensions library to your build.

=== Current Release

If you are using Eclipse or a Maven Tycho build, you can use the p2 repository 
`https://dl.bintray.com/boereck/xtensions-p2/Xtensions/1.0.0/`. 
Here is the repository info you can add to your maven `pom.xml` file:

[source,xml]
----
<repositories>
	<repository>
		<id>xtensions-p2</id>
		<layout>p2</layout>
		<url>https://dl.bintray.com/boereck/xtensions-p2/Xtensions/1.0.0/</url>
	</repository>
</repositories>
----

If you use a regular Maven build, simply add the following dependency. The library was added
to maven central.

[source,xml]
----
<dependencies>
	<dependency>
		<groupId>com.github.fraunhoferfokus.xtensions</groupId>
		<artifactId>de.fhg.fokus.xtensions</artifactId>
		<version>1.0.0</version>
	</dependency>
</dependencies>
----

If you are using gradle, add the following dependency:

[source,gradle]
----
compile 'com.github.fraunhoferfokus.xtensions:de.fhg.fokus.xtensions:1.0.0'
----

=== Using Snapshot Releases

Please add the following repository to your maven pom:

[source,xml]
----
<repositories>
	<repository>
		<id>jfrog-snapshots</id>
		<url>http://oss.jfrog.org/oss-snapshot-local/</url>
	</repository>
</repositories>
----

Then add the following dependency:

[source,xml]
----
<dependencies>
	<dependency>
		<groupId>com.github.fraunhoferfokus.xtensions</groupId>
		<artifactId>de.fhg.fokus.xtensions</artifactId>
		<version>1.1.0-SNAPSHOT</version>
	</dependency>
</dependencies> 
---- 

When using gradle, add the repository like this:

[source,gradle]
----
  repositories {
        mavenCentral()
        maven {
            url "http://oss.jfrog.org/oss-snapshot-local/"
        }
    }
----

And add the following dependency:

[source,gradle]
----
compile 'com.github.fraunhoferfokus.xtensions:de.fhg.fokus.xtensions:1.0.0-SNAPSHOT'
----


Currently there is no snapshot p2 update site, we hope to provide this shortly. +
Please have a look at the link:./docs/development.adoc[Build] section if you want to build the library from source on your own.


== Functionality and APIs

Most of the functionality provided by the library is described in a GitBook, based on the documentation files in this repository.
The book is made available link:https://boereck.gitbooks.io/xtensions[here].

An overview over the documentation files can be viewed directly on GitHub link:https://github.com/fraunhoferfokus/Xtensions/blob/master/SUMMARY.adoc[here]. 
GitHub has better code highlighting for Xtend snippets, so you might prefer this.

JavaDocs are currently not provided, but once released, a link to the respective javadoc.io site will be added.


== Development on the Library

Please have a look at the link:./docs/development.adoc[Development] document on how to get started with the development on the library
and some notes on contributing to the Xtensions project.


== Status of the Project

The following tasks are the next goals for this project, roughly in this order:

- [x] Complete this README.adoc file
 * [x] Complete Functionality section
 * [x] Complete IDE Setup section
- [x] Complete JavaDocs for all public methods
- [x] Cover each public method with test cases
- [x] Add Jacoco test coverage to maven build
- [x] Add source bundle build to maven config
- [x] Add JavaDoc bundle build to maven config
- [x] Move to a public GitHub repository
- [x] Create CI build on travis.io
 * [x] Add badge to this file when done
- [x] Publish Jacoco results to coveralls.io
 * [x] Add badge to this file when done
- [ ] Make Travis build push build results
 * [x] Maven libs to JFrog snapshots
 * [ ] p2 repository to Bintray
- [ ] Figure out how to best publish to Maven Central
- [ ] Release version 1.0.0 and update this file
- [ ] Add javadoc.io badge to this file
- [ ] Provide snapshot p2 repository
- [ ] Build GitBook in release build and push it to GitHub Pages
- [ ] Create a CHANGELOG.adoc file
