////
Copyright (c) 2017 Max Bureck (Fraunhofer FOKUS) and others.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html

Contributors:
    Max Bureck (Fraunhofer FOKUS) - initial text
////
= Provided Functionality
:toc: macro
:toclevels: 4
:toc-title: Contents of this document:


If you want to know how to add the library to your project, have a look at the link:../README.adoc[Introduction].

The sub-chapters of this chapter will provide a high level overview on how to use the different parts of this library.

When using the library in OSGi it is recommended to use package imports since the library may evolve
and split into multiple bundles in future releases.

The following chapters will give an overview over the most important extensions and types provided 
by the library. It does not include all methods. Please have a look at the sources or the JavaDocs
to explore all available functionality.

Most of the given examples in the following sections and some more are defined in the following 
test class:
link:https://github.com/fraunhoferfokus/Xtensions/blob/master/tests/de.fhg.fokus.xtensions.tests/src/de/fhg/fokus/xtensions/Showcase.xtend[Showcase.xtend]

If you want to see the overview all chapters of the documentation, have a look at the link:../SUMMARY.adoc[Content] page.
